server:
  port: 8183

spring:
  application:
    name: video-reco-service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/tech-flix-reco
    username:
    password:
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 10
      idle-timeout: 10000
      maximum-pool-size: 30

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8661/eureka
    instance:
      hostname: localhost