server:
  port: 8662

spring:
  application:
    name: gateway-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8661/eureka
    instance:
      hostname: localhost

zuul:
  host:
    connect-timeout-millis: 5000000
    socket-timeout-millis: 5000000
  ignored-services: '*'
  routes:
    resource-service:
      path: /resource/**
      serviceId: resource-service
      stripPrefix: true
    video-service:
      path: /video/**
      serviceId: video-service
      stripPrefix : true
    video-reco-service:
      path: /reco/**
      serviceId: video-reco-service
      stripPrefix: true
